spring:
  application:
    name: verification-service
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:system/oracle@10.243.136.57:1521:Eversbox
    username: DDL_INDUCTION
    password: DDL_INDUCTION

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none

server:
  port: 8072

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost